# Generated by Django 4.2 on 2023-04-25 11:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorysubscribers',
            unique_together={('category', 'subscriber')},
        ),
    ]
